global using QRCoder;
global using System.Drawing;
global using System.Text.Json;
global using Decimatio.Common.Interfaces;
global using Decimatio.Common.Options;
global using Azure.Storage.Blobs;
global using PuppeteerSharp;
global using System.Net.Mail;
global using System.Net;