global using Dapper;
global using Decimatio.Application.Interfaces.Repositories;
global using Decimatio.Domain.Entities;
global using Decimatio.Domain.QueryFilters;
global using Decimatio.Infraestructure.Connection;
global using Decimatio.Infraestructure.Repositories;
global using Microsoft.Data.SqlClient;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
